In [1]:
import pandas as pd

# Display all columns when printing DataFrames
pd.set_option("display.max_columns", None)

# Path to the dataset
file_path = "../data/raw/2019-Oct.csv"

# Read the first 10,000 rows for initial exploration
df = pd.read_csv(file_path, nrows=10000)

# Display the first five rows
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [2]:
print("Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

Shape: (10000, 9)

Column Names:
['event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']

Data Types:
event_time           str
event_type           str
product_id         int64
category_id        int64
category_code        str
brand                str
price            float64
user_id            int64
user_session         str
dtype: object

In [3]:
missing_values = df.isnull().sum()

missing_values

event_time          0
event_type          0
product_id          0
category_id         0
category_code    3277
brand            1442
price               0
user_id             0
user_session        0
dtype: int64

In [4]:
duplicate_rows = df.duplicated().sum()

print("Duplicate Rows:", duplicate_rows)

Duplicate Rows: 4

In [5]:
df.describe(include="all")

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
count,10000,10000,1.000000e+04,1.000000e+04,6723,8558,10000.000000,1.000000e+04,10000
unique,2084,3,NaN,NaN,103,671,NaN,NaN,3188
top,2019-10-01 02:34:58 UTC,view,NaN,NaN,electronics.smartphone,samsung,NaN,NaN,aa01487d-d46a-4704-9f1c-29613fbdaf1e
freq,21,9785,NaN,NaN,2830,1231,NaN,NaN,43
mean,NaN,NaN,1.024055e+07,2.055768e+18,NaN,NaN,294.079982,5.314151e+08,NaN
std,NaN,NaN,1.102505e+07,1.391996e+16,NaN,NaN,365.510001,1.691443e+07,NaN
min,NaN,NaN,1.002099e+06,2.053014e+18,NaN,NaN,0.000000,3.064418e+08,NaN
25%,NaN,NaN,1.005105e+06,2.053014e+18,NaN,NaN,62.940000,5.154591e+08,NaN
50%,NaN,NaN,5.100564e+06,2.053014e+18,NaN,NaN,159.330000,5.280995e+08,NaN
75%,NaN,NaN,1.620033e+07,2.053014e+18,NaN,NaN,362.940000,5.480955e+08,NaN
max,NaN,NaN,5.300000e+07,2.172371e+18,NaN,NaN,2574.070000,5.554648e+08,NaN

In [6]:
columns = [
    "event_type",
    "category_code",
    "brand"
]

for column in columns:
    print(f"\n{column}")
    print(df[column].value_counts().head(10))

event_type
event_type
view        9785
purchase     118
cart          97
Name: count, dtype: int64

category_code
category_code
electronics.smartphone               2830
electronics.clocks                    350
computers.notebook                    294
electronics.audio.headphone           259
appliances.environment.vacuum         153
electronics.video.tv                  139
appliances.kitchen.refrigerators      139
appliances.kitchen.washer             139
appliances.environment.air_heater     133
apparel.shoes.keds                    130
Name: count, dtype: int64

brand
brand
samsung     1231
apple       1039
xiaomi       698
huawei       306
lucente      128
bosch        118
elenberg     102
lg           101
lenovo        95
acer          95
Name: count, dtype: int64